version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/{{cookiecutter.collection_name}}/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/{{cookiecutter.collection_name}}/"
    schedule:
      interval: "daily"
